name: Cypress Tests

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Cypress tests
        run: |
         docker build -t cypress-tests:latest -f docker/Dockerfile .

      - name: List Docker images
        run: docker images

      - name: Run Cypress tests
        run: |
          docker run --rm \
          -v ${{github.workspace}}:/app \
          -w /app \
          cypress-tests:latest
