name: Cypress Tests

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Cypress tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: cypress-tests
        env:
          CI: true

      - name: Run Cypress tests
        run: |
          docker run --rm cypress-tests
